quarkus.devservices.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.http.cors.enabled=true
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/rxlight?sslmode=disable
%prod.quarkus.datasource.jdbc.url=${DATASOURCE}
quarkus.datasource.username=${DATASOURCE_USERNAME}
quarkus.datasource.password=${DATASOURCE_PASSWORD}
quarkus.hibernate-orm.database.generation=none
quarkus.http.port=8000
quarkus.application.name=rxlight-api
%dev.quarkus.redis.hosts[0]=redis://localhost:6379/0?protocol=resp3
%prod.quarkus.redis.hosts[0]=redis://:${REDIS_AUTH}@${REDIS_HOST}:${REDIS_PORT}/0?protocol=resp3
quarkus.http.access-log.enabled=true
%dev.quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b %Dms
# flyway
quarkus.flyway.sql-migration-prefix=V
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.enabled=true
quarkus.flyway.locations=classpath:db/migration
quarkus.flyway.schemas=public
# 1. Enable OpenTelemetry
%dev.quarkus.otel.enabled=false
%prod.quarkus.otel.enabled=true
%prod.quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
# 2. Enable JSON Logging
%dev.quarkus.log.console.json=false
%prod.quarkus.log.console.json=true
# 3. Rename OpenTelemetry Trace and Span IDs
# By default, Quarkus JSON logging recognizes traceId and spanId
# 4. Optional: Include other OTel metadata in MDC
%prod.quarkus.log.console.json.mdc.enabled=true
quarkus.otel.traces.enabled=true
%prod.quarkus.otel.metrics.enabled=true
quarkus.websockets-next.server.auto-ping-interval=PT30S
%dev.quarkus.event.bus.enabled=false
openrxlight.token.store.type=REDIS
rxlight.wechat.mini-program.app-id=${WECHAT_MINI_PROGRAM_APPID}
rxlight.wechat.mini-program.app-secret=${WECHAT_MINI_PROGRAM_APPSECRET}
# rxlight.wechat.mini-program.counterparty-id=${WECHAT_COUNTERPARTY_ID}
rxlight.wechat.mini-program.api-v3-key=${WECHAT_PAY_APIV3KEY}
rxlight.wechat.mini-program.service-id=${WECHAT_MINI_PROGRAM_SERVICE_ID}
rxlight.wechat.mini-program.enabled=true
%dev.openrxlight.api.url=http://localhost:8001
%prod.openrxlight.api.url=${OPENRXLIGHT_API_URL}
openrxlight.api.enabled=true
openrxlight.api.client-id=${OPENRXLIGHT_API_CLIENTID}
openrxlight.api.client-secret=${OPENRXLIGHT_API_CLIENTSECRET}
openrxlight.api.signature-priv-key=${OPENRXLIGHT_API_SIGNATURE_PRI_KEY}
openrxlight.api.signature-pub-key=${OPENRXLIGHT_API_SIGNATURE_PUB_KEY}
rxlight.fs.type=s3
rxlight.fs.bucket-name=${FS_BUCKET_NAME}
rxlight.fs.endpoint=${FS_ENDPOINT}
rxlight.fs.access-key=${ALIBABA_CLOUD_ACCESS_KEY_ID}
rxlight.fs.secret-key=${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
rxlight.fs.region=${FS_REGION}
rxlight.fs.enabled=false
rxlight.ai.thirdparty.enabled=false
rxlight.notification.sms.vender=alicloud
rxlight.notification.sms.enabled=true
# alicloud.access-key-id=${ALIBABA_CLOUD_ACCESS_KEY_ID}
# alicloud.access-key-secret=${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
quarkus.flyway.placeholders.admin_email=${ADMIN_EMAIL}
quarkus.flyway.placeholders.lark_app_id=${LARK_APP_ID}
quarkus.flyway.placeholders.lark_app_secret=${LARK_APP_SECRET}
quarkus.flyway.placeholders.lark_app_encrypt_key=${LARK_APP_ENCRYPT_KEY}
quarkus.flyway.placeholders.lark_app_verification_token=${LARK_APP_VERIFICATION_TOKEN}
quarkus.flyway.placeholders.openrxlight_client_id=${OPENRXLIGHT_API_CLIENTID}
quarkus.flyway.placeholders.openrxlight_client_secret=${OPENRXLIGHT_API_CLIENTSECRET}
quarkus.flyway.placeholders.openrxlight_signature_priv_key=${OPENRXLIGHT_API_SIGNATURE_PRI_KEY}
quarkus.flyway.placeholders.openrxlight_signature_pub_key=${OPENRXLIGHT_API_SIGNATURE_PUB_KEY}
rxlight.llm.api-key=${LLM_API_KEY}
rxlight.llm.base-url=${LLM_BASE_URL}
openrxlight.ai.translator.type=alicloud
openrxlight.ai.translator.alicloud.region-id=${ALICLOUD_REGION_ID}
openrxlight.ai.translator.alicloud.endpoint=${ALICLOUD_TRANSLATOR_ENDPOINT}
openrxlight.ai.translator.alicloud.access-key=${ALICLOUD_ACCESS_KEY_ID}
openrxlight.ai.translator.alicloud.secret-key=${ALICLOUD_ACCESS_KEY_SECRET}
openrxlight.ai.audio.type=alicloud
openrxlight.ai.audio.alicloud.api-key=${LLM_API_KEY}
openrxlight.ai.audio.alicloud.tts-voice=${ALICLOUD_TTS_VOICE}