CREATE TABLE IF NOT EXISTS agent_app (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Unique identifier
    app_id VARCHAR(64) NOT NULL,
    -- Application ID
    app_secret TEXT NOT NULL,
    -- Application secret
    app_type INTEGER NOT NULL DEFAULT 0,
    -- Application type
    credential JSONB NULL,
    -- Credential information (JSON)
    scenario INTEGER NOT NULL DEFAULT 0,
    -- Scenario type
    enabled BOOLEAN NOT NULL DEFAULT true,
    -- Whether the application is enabled
    openrxlight JSONB NOT NULL -- OpenRxLight configuration (JSON)
);
CREATE UNIQUE INDEX idx_agent_app_app_id ON agent_app (app_type, app_id);
COMMENT ON TABLE agent_app IS 'Agent application information';
COMMENT ON COLUMN agent_app.id IS 'Unique identifier';
COMMENT ON COLUMN agent_app.app_id IS 'Application ID';
COMMENT ON COLUMN agent_app.app_secret IS 'Application secret';
COMMENT ON COLUMN agent_app.app_type IS 'Application type';
COMMENT ON COLUMN agent_app.credential IS 'Credential information (JSON)';
COMMENT ON COLUMN agent_app.scenario IS 'Scenario type';
COMMENT ON COLUMN agent_app.enabled IS 'Whether the application is enabled';
COMMENT ON COLUMN agent_app.openrxlight IS 'OpenRxLight configuration (JSON)';