CREATE TABLE IF NOT EXISTS "order" (
    id BIGINT PRIMARY KEY DEFAULT next_snowflake_id(),
    order_no VARCHAR(255) NOT NULL,
    third_party_order_no VARCHAR(255) NOT NULL,
    order_type SMALLINT NOT NULL,
    status SMALLINT NOT NULL,
    station_id VARCHAR(255) NOT NULL,
    space_id VARCHAR(255) NOT NULL,
    range_id VARCHAR(255) NOT NULL,
    space_no VARCHAR(255) NOT NULL,
    account_id UUID NULL,
    plate_no VARCHAR(64),
    phone_no VARCHAR(32),
    charge_start_time TIMESTAMP,
    charge_end_time TIMESTAMP,
    charged_power INTEGER,
    service_ccy INTEGER,
    charge_ccy INTEGER,
    total_ccy INTEGER,
    start_soc INTEGER,
    end_soc INTEGER,
    created_time TIMESTAMP NOT NULL,
    updated_time TIMESTAMP NOT NULL,
    additional_fees JSONB,
    device_ids BIGINT [],
    source_type SMALLINT NOT NULL,
    transaction_id UUID,
    pay_type SMALLINT NOT NULL,
    car_model_id VARCHAR(255) NOT NULL
);
COMMENT ON TABLE "order" IS 'operation orders details';
CREATE UNIQUE INDEX IF NOT EXISTS idx_order_order_no ON "order"(order_no);
CREATE INDEX IF NOT EXISTS idx_order_station ON "order" (
    station_id,
    range_id,
    space_id,
    created_time,
    status
);
CREATE INDEX IF NOT EXISTS idx_order_user_info ON "order" (phone_no, plate_no, created_time, status);
CREATE INDEX IF NOT EXISTS idx_order_account_id ON "order" (account_id, created_time, status);
CREATE INDEX IF NOT EXISTS idx_order_third_party_order_no ON "order"(
    third_party_order_no,
    source_type,
    created_time,
    status
);
COMMENT ON COLUMN "order".id IS 'Primary key, auto-incremented order ID';
COMMENT ON COLUMN "order".order_no IS 'Unique order number generated by RxLight system';
COMMENT ON COLUMN "order".third_party_order_no IS 'Order number from third-party platform';
COMMENT ON COLUMN "order".order_type IS 'Type of the order, e.g., charging, parking, etc.';
COMMENT ON COLUMN "order".status IS 'Current status of the order';
COMMENT ON COLUMN "order".station_id IS 'ID of the station where the order was created';
COMMENT ON COLUMN "order".space_id IS 'ID of the parking/charging space associated with the order';
COMMENT ON COLUMN "order".range_id IS 'ID of the range or area associated with the order';
COMMENT ON COLUMN "order".space_no IS 'Number or identifier of the parking  space';
COMMENT ON COLUMN "order".account_id IS 'ID of the user account associated with the order';
COMMENT ON COLUMN "order".plate_no IS 'Vehicle plate number associated with the order';
COMMENT ON COLUMN "order".phone_no IS 'Phone number of the user who created the order';
COMMENT ON COLUMN "order".charge_start_time IS 'Timestamp when the charging started';
COMMENT ON COLUMN "order".charge_end_time IS 'Timestamp when the charging ended';
COMMENT ON COLUMN "order".charged_power IS 'Total power charged during the session (in kWh)';
COMMENT ON COLUMN "order".service_ccy IS 'Service fee charged for the order (in cents)';
COMMENT ON COLUMN "order".charge_ccy IS 'Charging fee charged for the order (in cents)';
COMMENT ON COLUMN "order".total_ccy IS 'Total fee charged for the order (in cents)';
COMMENT ON COLUMN "order".start_soc IS 'State of Charge (SOC) at the start of the charging session (in %)';
COMMENT ON COLUMN "order".end_soc IS 'State of Charge (SOC) at the end of the charging session (in %)';
COMMENT ON COLUMN "order".created_time IS 'Timestamp when the order was created';
COMMENT ON COLUMN "order".updated_time IS 'Timestamp when the order was last updated';
COMMENT ON COLUMN "order".additional_fees IS 'Additional fees associated with the order in JSON format';
COMMENT ON COLUMN "order".source_type IS 'Source platform type of the order';
COMMENT ON COLUMN "order".device_ids IS 'IDs of devices involved in the order';
COMMENT ON COLUMN "order".transaction_id IS 'Transaction ID associated with the order';