CREATE TABLE IF NOT EXISTS user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id UUID NOT NULL,
    account_type INT NOT NULL,
    display_name VARCHAR(255) NULL,
    avatar TEXT NULL,
    account_info JSONB NULL,
    external_accounts JSONB NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    source INT NOT NULL,
    role_types INT [] NULL,
    last_login_time TIMESTAMP WITHOUT TIME ZONE NULL,
    language VARCHAR(16) NULL DEFAULT 'zh-CN'
);
CREATE UNIQUE INDEX uq_user_accounts_account_id ON user_accounts(account_id, account_type);
CREATE INDEX idx_user_accounts_external_accounts ON user_accounts USING GIN (external_accounts jsonb_path_ops);
COMMENT ON TABLE user_accounts IS 'Table to store user account information';
COMMENT ON COLUMN user_accounts.account_id IS 'Unique identifier for the user account';
COMMENT ON COLUMN user_accounts.display_name IS 'Display name of the user';
COMMENT ON COLUMN user_accounts.avatar IS 'URL or path to the avatar image';
COMMENT ON COLUMN user_accounts.account_info IS 'Additional information about the account in JSON format';
COMMENT ON COLUMN user_accounts.external_accounts IS 'Linked external accounts in JSON format';
COMMENT ON COLUMN user_accounts.created_time IS 'Timestamp when the account was created';
COMMENT ON COLUMN user_accounts.updated_time IS 'Timestamp when the account was last updated';
COMMENT ON COLUMN user_accounts.is_active IS 'Indicates if the account is active';
COMMENT ON COLUMN user_accounts.source IS 'Source of the account (e.g., internal, external)';
COMMENT ON COLUMN user_accounts.last_login_time IS 'Timestamp of the last login';
COMMENT ON COLUMN user_accounts.account_type IS 'Type of the account (e.g., consumer, operator, merchant)';
COMMENT ON COLUMN user_accounts.role_types IS 'Array of role types assigned to the account';
COMMENT ON COLUMN user_accounts.language IS 'Preferred language of the user, ISO-639-1 code, e.g., zh-CN, en-US';