CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Unique identifier
    user_id UUID NOT NULL,
    -- User ID
    context_id VARCHAR(128) NULL,
    -- Context ID
    app_id INTEGER NOT NULL,
    -- Application ID
    openrxlight_message_id VARCHAR(128) NOT NULL,
    -- OpenRxLight Message ID
    app_message_id VARCHAR(128) NOT NULL,
    -- App Message ID
    content TEXT NULL,
    -- Message content
    callback JSONB NULL,
    -- Callback information (JSON)
    attachments JSONB NULL,
    -- Attachments information (JSON)
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Creation timestamp
    extra JSONB NULL
    -- Extra information (JSON)
);
CREATE UNIQUE INDEX idx_chat_messages_unique ON chat_messages (
    app_id,
    user_id,
    app_message_id,
    openrxlight_message_id
);
CREATE INDEX IF NOT EXISTS idx_chat_messages_create_at_index ON chat_messages (app_id, user_id, created_at);
COMMENT ON TABLE chat_messages IS 'Chat messages';
COMMENT ON COLUMN chat_messages.id IS 'Unique identifier';
COMMENT ON COLUMN chat_messages.user_id IS 'User ID';
COMMENT ON COLUMN chat_messages.context_id IS 'Context ID';
COMMENT ON COLUMN chat_messages.app_id IS 'Application ID';
COMMENT ON COLUMN chat_messages.openrxlight_message_id IS 'OpenRxLight Message ID';
COMMENT ON COLUMN chat_messages.app_message_id IS 'App Message ID';
COMMENT ON COLUMN chat_messages.content IS 'Message content';
COMMENT ON COLUMN chat_messages.callback IS 'Callback information (JSON)';
COMMENT ON COLUMN chat_messages.attachments IS 'Attachments information (JSON)';
COMMENT ON COLUMN chat_messages.created_at IS 'Creation timestamp';
COMMENT ON COLUMN chat_messages.extra IS 'Extra information (JSON)';