package cn.ggsn.openrxlight.utils;

import java.nio.charset.StandardCharsets;
import java.security.Security;
import java.util.Base64;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;

import org.apache.commons.codec.digest.DigestUtils;
import org.apache.commons.lang.StringUtils;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.mindrot.jbcrypt.BCrypt;

import cn.ggsn.openrxlight.DataCrypto;
import cn.ggsn.openrxlight.DigitalSignature;

public class EncryptUtil {
    private static final String VOCABULARY = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    static {
        if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
            Security.addProvider(new BouncyCastleProvider());
        }
    }

    public static String encrypt(String plaintext, String encryptionKey, String iv, DataCrypto dataCrypto)
            throws Exception {
        if (StringUtils.isBlank(plaintext)) {
            return null;
        }
        // Placeholder for encryption logic
        SecretKey secretKey = dataCrypto.getSecretKey(encryptionKey.getBytes(StandardCharsets.UTF_8));
        String provider = dataCrypto.getProvider();
        Cipher cipher = null;
        if (StringUtils.isBlank(provider)) {
            cipher = Cipher.getInstance(String.format("%s/%s/%s",
                    dataCrypto.getAlgorithm(),
                    dataCrypto.getCipherMode(),
                    dataCrypto.getPadding()));
        } else {
            cipher = Cipher.getInstance(String.format("%s/%s/%s",
                    dataCrypto.getAlgorithm(),
                    dataCrypto.getCipherMode(),
                    dataCrypto.getPadding(), provider));
        }

        cipher.init(Cipher.ENCRYPT_MODE, secretKey, dataCrypto.getAlgorithmSpec(iv));
        byte[] cipherText = cipher.doFinal(plaintext.getBytes(StandardCharsets.UTF_8));

        return Base64.getEncoder().encodeToString(cipherText);
    }

    public static String decrypt(String ciphertext, String decryptionKey, String iv, DataCrypto dataCrypto)
            throws Exception {
        if (StringUtils.isBlank(ciphertext)) {
            return null;
        }
        SecretKey secretKey = dataCrypto.getSecretKey(decryptionKey.getBytes());
        String provider = dataCrypto.getProvider();
        Cipher cipher = null;
        if (StringUtils.isBlank(provider)) {
            cipher = Cipher.getInstance(String.format("%s/%s/%s",
                    dataCrypto.getAlgorithm(),
                    dataCrypto.getCipherMode(),
                    dataCrypto.getPadding()));
        } else {
            cipher = Cipher.getInstance(String.format("%s/%s/%s",
                    dataCrypto.getAlgorithm(),
                    dataCrypto.getCipherMode(),
                    dataCrypto.getPadding(), provider));
        }
        cipher.init(Cipher.DECRYPT_MODE, secretKey, dataCrypto.getAlgorithmSpec(iv));
        byte[] plainText = cipher.doFinal(Base64.getDecoder().decode(ciphertext));

        return new String(plainText, StandardCharsets.UTF_8);
    }

    public static String generateNonce(int length) {
        StringBuilder nonceBuilder = new StringBuilder(length);
        java.security.SecureRandom random = new java.security.SecureRandom();
        for (int i = 0; i < length; i++) {
            int index = random.nextInt(VOCABULARY.length());
            nonceBuilder.append(VOCABULARY.charAt(index));
        }

        return nonceBuilder.toString();
    }

    public static String sign(String plaintext, String key, DigitalSignature digitalSign) throws Exception {
        byte[] md5Plaintext = DigestUtils.md5(plaintext);
        byte[] signedData = digitalSign.sign(md5Plaintext, key);
        return Base64.getEncoder().encodeToString(signedData);
    }

    public static void verify(String plaintext, String originSignature, String pubKey,
            DigitalSignature signAlgorithm) throws Exception {
        byte[] decodedOriginSign = Base64.getDecoder().decode(originSignature);
        signAlgorithm.verify(DigestUtils.md5(plaintext), pubKey, decodedOriginSign);
    }

    public static String bcrypt(String password, String salt) {
        if (StringUtils.isBlank(password) || StringUtils.isBlank(salt)) {
            return null;
        }
        // The salt must be a valid BCrypt salt string (generated by BCrypt.gensalt)
        return BCrypt.hashpw(password, salt);
    }

    public static boolean bcryptCheck(String password, String hashed, String salt) {
        if (StringUtils.isBlank(password) || StringUtils.isBlank(hashed) || StringUtils.isBlank(salt)) {
            return false;
        }

        String hashedPassword = bcrypt(password, salt);
        return StringUtils.equals(hashedPassword, hashed);
    }

    public static String genSalt() {
        return BCrypt.gensalt();
    }
}
